# Generated by Django 2.2.1 on 2019-05-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_from', models.CharField(max_length=100, verbose_name='address from')),
                ('address_to', models.CharField(max_length=100, verbose_name='address to')),
                ('mission', models.CharField(max_length=20, verbose_name='mission')),
                ('volume', models.FloatField(verbose_name='volume')),
                ('commission', models.FloatField(verbose_name='commission')),
                ('committed', models.DateTimeField(verbose_name='committed')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Wallet')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
