# Generated by Django 2.2.1 on 2019-05-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.CharField(default='', max_length=100, verbose_name='comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address_from',
            field=models.CharField(db_index=True, max_length=100, verbose_name='address from'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address_to',
            field=models.CharField(db_index=True, max_length=100, verbose_name='address to'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='committed',
            field=models.DateTimeField(db_index=True, verbose_name='committed'),
        ),
    ]
