# Generated by Django 2.2.1 on 2019-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20190519_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['committed'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='volume_btc',
            field=models.FloatField(default=1, verbose_name='volume_btc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='volume_usd',
            field=models.FloatField(default=1, verbose_name='volume_usd'),
            preserve_default=False,
        ),
    ]
