# Generated by Django 2.2.1 on 2019-05-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20190520_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='mission',
        ),
    ]
