# Generated by Django 2.2.1 on 2019-05-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_transaction_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mission',
            field=models.CharField(choices=[('supplement', 'supplement'), ('conclusion', 'conclusion'), ('delegation', 'delegation'), ('delegate_change', 'delegate change'), ('delegate_remove', 'delegate remove'), ('payment', 'payment')], default='delegate_change', max_length=20, verbose_name='mission'),
            preserve_default=False,
        ),
    ]
