# Generated by Django 2.2.1 on 2019-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transaction_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='address_from',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='address from'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address_to',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='address to'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mission',
            field=models.CharField(choices=[('supplement', 'supplement'), ('conclusion', 'conclusion'), ('delegation', 'delegation'), ('delegate_change', 'delegate change'), ('delegate_remove', 'delegate remove'), ('payment', 'payment')], db_index=True, max_length=20, verbose_name='mission'),
        ),
    ]
