# Generated by Django 2.2.1 on 2019-05-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20190526_1948'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'address_from', 'address_to', 'volume', 'committed'), name='unique_transaction'),
        ),
    ]
