# Generated by Django 2.2.1 on 2019-05-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20190526_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-committed'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
