# Generated by Django 2.2.1 on 2019-05-27 09:21

from django.db import migrations, models

def delete_all_transactions(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    transaction_model = apps.get_model('transaction', 'Transaction')
    transaction_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20190526_2141'),
    ]

    operations = [
        migrations.RunPython(delete_all_transactions),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tr_hash',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='hash'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'tr_hash'), name='unique_transaction'),
        ),
    ]
