# Generated by Django 2.2.1 on 2019-05-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20190527_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='volume_btc',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='volume_usd',
        ),
    ]
