# Generated by Django 2.2.1 on 2019-06-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_hash', models.CharField(db_index=True, max_length=100, verbose_name='hash')),
                ('address_from', models.CharField(db_index=True, max_length=100, null=True, verbose_name='address from')),
                ('address_to', models.CharField(db_index=True, max_length=100, null=True, verbose_name='address to')),
                ('mission', models.CharField(choices=[('supplement', 'supplement'), ('conclusion', 'conclusion'), ('delegation', 'delegation'), ('delegate_change', 'delegate change'), ('delegate_remove', 'delegate remove'), ('payment', 'payment')], db_index=True, max_length=20, verbose_name='mission')),
                ('volume', models.FloatField(verbose_name='volume')),
                ('commission', models.FloatField(verbose_name='commission')),
                ('committed', models.DateTimeField(db_index=True, verbose_name='committed')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='comment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-committed'],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'tr_hash'), name='unique_transaction'),
        ),
    ]
