# Generated by Django 2.2.1 on 2019-06-20 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('sign', models.CharField(default='?', max_length=10, verbose_name='sign')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='code')),
                ('net', models.CharField(default='?', max_length=10, verbose_name='net')),
                ('initialized', models.BooleanField(default=False, verbose_name='initialized')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='currency', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='color')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='updated')),
                ('initialized', models.BooleanField(default=False, verbose_name='initialized')),
                ('updated_from_2nd_svr', models.DateTimeField(blank=True, null=True, verbose_name='updated_from_2nd_svr')),
                ('transactions_detail', models.TextField(default='', verbose_name='Transactions update detail')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='datetime')),
                ('usd', models.FloatField(null=True, verbose_name='USD')),
                ('btc', models.FloatField(null=True, verbose_name='BTC')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Currency')),
            ],
            options={
                'verbose_name': 'currency rate',
                'verbose_name_plural': 'currencies rates',
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('currency', 'address'), name='unique_net_address'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('currency', 'datetime'), name='unique_currency_datetime'),
        ),
    ]
