# Generated by Django 2.2.1 on 2019-06-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('url', models.URLField(verbose_name='url')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='currency_social', verbose_name='icon')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='wallet.Currency')),
            ],
            options={
                'verbose_name': 'currency social',
                'verbose_name_plural': 'currencies social',
            },
        ),
    ]
