# Generated by Django 2.2.1 on 2019-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_currencystatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
