# Generated by Django 2.2.1 on 2019-05-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='chart_date_from',
        ),
        migrations.RemoveField(
            model_name='account',
            name='chart_date_to',
        ),
    ]
