# Generated by Django 2.2.1 on 2019-06-20 17:26

import account.managers.account
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190620_2022'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.managers.account.UserManager()),
            ],
        ),
    ]
