# Generated by Django 2.2.1 on 2019-05-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'net',
                'verbose_name_plural': 'nets',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('created', models.DateTimeField(verbose_name='created')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Currency')),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Net')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='datetime')),
                ('usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='USD')),
                ('btc', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='BTC')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Currency')),
            ],
            options={
                'verbose_name': 'currency rate',
                'verbose_name_plural': 'currencies rates',
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('net', 'address'), name='unique_net_address'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('currency', 'datetime'), name='unique_currency_datetime'),
        ),
    ]
