# Generated by Django 2.2.1 on 2019-05-26 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20190519_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated'),
            preserve_default=False,
        ),
    ]
