# Generated by Django 2.2.1 on 2019-05-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='btc',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='BTC'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usd',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='USD'),
        ),
    ]
