# Generated by Django 2.2.1 on 2019-05-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20190527_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='initialized',
            field=models.BooleanField(default=False, verbose_name='initialized'),
        ),
    ]
