# Generated by Django 2.2.1 on 2019-05-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_wallet_initialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='initialized',
            field=models.BooleanField(default=False, verbose_name='initialized'),
        ),
    ]
