# Generated by Django 2.2.1 on 2019-05-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20190527_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated'),
        ),
    ]
