# Generated by Django 2.2.1 on 2019-05-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20190528_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='currency', verbose_name='icon'),
        ),
    ]
