# Generated by Django 2.2.1 on 2019-05-29 19:24

from django.db import migrations, models


def delete_copies(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    transaction_model = apps.get_model('wallet', 'Wallet')
    for t in transaction_model.objects.all():
        amount = transaction_model.objects.filter(
            currency=t.currency,
            address=t.address
        ).exclude(pk=t.pk).count()
        if amount > 0:
            t.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_currency_icon'),
    ]

    operations = [
        migrations.RunPython(delete_copies),
        migrations.RemoveConstraint(
            model_name='wallet',
            name='unique_net_address',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='net',
        ),
        migrations.AddField(
            model_name='currency',
            name='net',
            field=models.CharField(default='?', max_length=10, verbose_name='net'),
        ),
        migrations.AddField(
            model_name='currency',
            name='sign',
            field=models.CharField(default='?', max_length=10, verbose_name='sign'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('currency', 'address'), name='unique_net_address'),
        ),
        migrations.DeleteModel(
            name='Net',
        ),
    ]
