# Generated by Django 2.2.1 on 2019-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20190529_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created'),
        ),
    ]
