# Generated by Django 2.2.1 on 2019-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20190530_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='btc',
            field=models.FloatField(null=True, verbose_name='BTC'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usd',
            field=models.FloatField(null=True, verbose_name='USD'),
        ),
    ]
