# Generated by Django 2.2.1 on 2019-05-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20190530_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transactions_updated',
        ),
    ]
