# Generated by Django 2.2.1 on 2019-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_remove_wallet_transactions_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='color'),
        ),
    ]
