# Generated by Django 2.2.1 on 2019-06-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_wallet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='updated_from_2nd_svr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated_from_2nd_svr'),
        ),
    ]
